---
- name: install gitea with sql database trough docker
  hosts: linux_machines
  become: true
  roles:
    - docker-role
  tasks:

   # Run ansible-playbook -K gitea.yaml to start this ansible script, -K to ask for the password

    - name: Update package cache
      ansible.builtin.yum:
        update_cache: true

    - name: Deploy MySQL database
      community.docker.docker_container:
        name: MySQL
        image: mysql:latest
        env: 
          MYSQL_ROOT_PASSWORD: uiopuiop
          MYSQL_USER: gitea
          MYSQL_PASSWORD: uiopuiop
          MYSQL_DATABASE: gitea
        volumes:
          - "./mysql:/var/lib/mysql"
        restart_policy: on-failure
        ports:
          - "3306:3306"
    
    - name: Retrieve MySQL container IP
      docker_container_info:
        name: MySQL
      register: result

    - name: Print ip from MySQL container
      debug:
        var: result.container.NetworkSettings.IPAddress
      when: result.exists
    
    - name: Deploy gitea server
      community.docker.docker_container:
        name: gitea
        image: gitea/gitea:1.19-nightly
        env:
          USER_UID: "1000"
          USER_GID: "1000"
          GITEA__database__DB_TYPE: mysql
          GITEA__database__HOST: "{{result.container.NetworkSettings.IPAddress}}:3306"
          GITEA__database__NAME: gitea
          GITEA__database__USER: gitea
          GITEA__database__PASSWD: uiopuiop
        volumes:
          - "./gitea:/data"
          - "/etc/timezone:/etc/timezone:ro"
          - "/etc/localtime:/etc/localtime:ro"
        ports:
          - "3000:3000"
          - "222:22"
        

